# Generated by Django 4.2.9 on 2026-02-10 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mdm', '0001_initial'),
        ('inventory', '0001_initial'),
        ('documents', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='documents.document'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='mdm.location'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='mdm.sku'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='mdm.location'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='mdm.company'),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='mdm.location'),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='mdm.sku'),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceiptscan',
            name='barcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='mdm.skubarcode'),
        ),
        migrations.AddField(
            model_name='goodsreceiptscan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='mdm.company'),
        ),
        migrations.AddField(
            model_name='goodsreceiptscan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceiptscan',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_scans', to='documents.document'),
        ),
        migrations.AddField(
            model_name='goodsreceiptscan',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_scans', to='mdm.location'),
        ),
        migrations.AddField(
            model_name='goodsreceiptscan',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_scans', to='mdm.sku'),
        ),
        migrations.AddField(
            model_name='goodsreceiptscan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['sku', '-movement_date'], name='inv_movemen_sku_id_a18a85_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['from_location', '-movement_date'], name='inv_movemen_from_lo_cf1515_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['to_location', '-movement_date'], name='inv_movemen_to_loca_d2f1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['company', 'location', 'status'], name='inv_balance_company_75b16f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['sku', 'status'], name='inv_balance_sku_id_e8735e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorybalance',
            unique_together={('company', 'sku', 'location', 'condition')},
        ),
        migrations.AddIndex(
            model_name='goodsreceiptscan',
            index=models.Index(fields=['company', 'result', '-scanned_at'], name='inv_goods_r_company_dfa321_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceiptscan',
            index=models.Index(fields=['barcode_value', '-scanned_at'], name='inv_goods_r_barcode_1ec652_idx'),
        ),
    ]
