# Generated by Django 4.2.9 on 2026-02-20 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mdm', '0002_sku_size_alter_user_company'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamagedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode_value', models.CharField(db_index=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=15)),
                ('damage_type', models.CharField(choices=[('physical', 'Physical Damage'), ('packaging', 'Packaging Damage'), ('quality', 'Quality Issue'), ('missing_parts', 'Missing Parts'), ('wrong_item', 'Wrong Item'), ('expired', 'Expired/Near Expiry'), ('other', 'Other')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('minor', 'Minor - Cosmetic only'), ('major', 'Major - Affects functionality'), ('critical', 'Critical - Unusable')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('suggested_action', models.CharField(blank=True, choices=[('return_to_vendor', 'Return to Vendor'), ('dispose', 'Dispose'), ('repair', 'Repair'), ('discount_sale', 'Discount Sale'), ('use_as_is', 'Use As-Is')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='damage_photos/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='mdm.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damaged_items', to='mdm.location')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_damages', to=settings.AUTH_USER_MODEL)),
                ('scan_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_records', to='inventory.goodsreceiptscan')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='damage_records', to='mdm.sku')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_damaged_item',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['company', 'damage_type', '-recorded_at'], name='inv_damaged_company_b8ea6b_idx'), models.Index(fields=['severity', '-recorded_at'], name='inv_damaged_severit_f0aca2_idx'), models.Index(fields=['sku', '-recorded_at'], name='inv_damaged_sku_id_bb9512_idx')],
            },
        ),
    ]
