# Generated by Django 4.2.9 on 2026-02-20 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mdm', '0003_sku_lifecycle_status'),
        ('documents', '__first__'),
        ('inventory', '0003_damageditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductJourneyCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('fabric_sourced', 'Fabric Sourced'), ('design_approved', 'Design Approved'), ('in_production', 'In Production'), ('received', 'Received'), ('quality_check', 'Quality Check'), ('storage', 'Storage'), ('picked', 'Picked'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], max_length=50)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('delayed', 'Delayed')], max_length=20)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('expected_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='mdm.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.location')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journey_checkpoints', to='mdm.sku')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_product_journey_checkpoint',
                'ordering': ['created_at'],
            },
        ),
    ]
