# Generated by Django 4.2.9 on 2026-02-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productjourneycheckpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='productjourneycheckpoint',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='journey_attachments/'),
        ),
        migrations.AddField(
            model_name='productjourneycheckpoint',
            name='measurement_unit',
            field=models.CharField(blank=True, help_text='e.g. Meters, Kg', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productjourneycheckpoint',
            name='measurement_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='e.g. Meters of fabric', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productjourneycheckpoint',
            name='stage',
            field=models.CharField(choices=[('fabric_sourced', 'Fabric Sourced'), ('fabric_dispatched', 'Fabric Dispatched'), ('design_approved', 'Design Approved'), ('in_production', 'In Production'), ('shoot', 'Shoot / Photography'), ('received', 'Received'), ('quality_check', 'Quality Check'), ('storage', 'Storage'), ('picked', 'Picked'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], max_length=50),
        ),
    ]
