# Generated by Django 4.2.9 on 2026-02-25 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0006_fabric_photo_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_add_kanban_checkpoint_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStockSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('opening_stock', models.DecimalField(decimal_places=3, default=0, help_text='Stock at start of day', max_digits=15)),
                ('closing_stock', models.DecimalField(decimal_places=3, default=0, help_text='Stock at end of day', max_digits=15)),
                ('units_sold', models.DecimalField(decimal_places=3, default=0, help_text='Total sold during the day', max_digits=15)),
                ('units_received', models.DecimalField(decimal_places=3, default=0, help_text='Total received during the day', max_digits=15)),
                ('units_transferred_in', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('units_transferred_out', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('units_adjusted', models.DecimalField(decimal_places=3, default=0, help_text='Manual adjustments (positive or negative)', max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='mdm.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_snapshots', to='mdm.location')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_snapshots', to='mdm.sku')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_daily_stock_snapshot',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['company', 'location', '-snapshot_date'], name='inv_daily_s_company_80b23d_idx'), models.Index(fields=['sku', '-snapshot_date'], name='inv_daily_s_sku_id_a5c97a_idx')],
                'unique_together': {('company', 'snapshot_date', 'sku', 'location')},
            },
        ),
    ]
