# Generated by Django 4.2.9 on 2026-02-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_dailystocksnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybalance',
            name='is_offer_eligible',
            field=models.BooleanField(default=False, help_text='Whether this unique SKU at this location is eligible for individual store offers'),
        ),
    ]
