# Generated by Django 4.2.9 on 2026-03-02 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mdm', '0014_sku_is_best_seller_sku_min_stock_level_and_more'),
        ('inventory', '0007_inventorybalance_is_offer_eligible'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('order_type', models.CharField(choices=[('new_production', 'New Production'), ('restock', 'Restock'), ('urgent_restock', 'Urgent Restock')], default='new_production', max_length=30)),
                ('po_status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_production', 'In Production'), ('partially_received', 'Partially Received'), ('completed', 'Completed'), ('short_closed', 'Short Closed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30)),
                ('order_date', models.DateField(help_text='When the production order was placed')),
                ('expected_delivery', models.DateField(blank=True, help_text='Expected delivery from factory', null=True)),
                ('actual_delivery', models.DateField(blank=True, help_text='When first goods were received', null=True)),
                ('triggered_by', models.CharField(choices=[('manual', 'Manual'), ('design_approval', 'Design Approval'), ('low_stock_alert', 'Low Stock Alert'), ('shopify_low', 'Shopify Low Stock')], default='manual', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='mdm.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(help_text='Warehouse where goods will be received', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_production_orders', to='mdm.location')),
                ('factory', models.ForeignKey(blank=True, help_text='Factory/vendor producing the goods', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='mdm.vendor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_production_order',
                'ordering': ['-order_date'],
            },
        ),
        migrations.AlterField(
            model_name='productjourneycheckpoint',
            name='stage',
            field=models.CharField(choices=[('fabric_sourced', 'Fabric Sourced'), ('fabric_dispatched', 'Fabric Dispatched'), ('design_approved', 'Design Approved'), ('production_ordered', 'Production Ordered'), ('production_confirmed', 'Production Confirmed'), ('in_production', 'In Production'), ('shoot', 'Shoot / Photography'), ('received', 'Received'), ('production_shortfall', 'Production Shortfall'), ('quality_check', 'Quality Check'), ('storage', 'Storage'), ('restock_triggered', 'Restock Triggered'), ('picked', 'Picked'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProductionOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_quantity', models.PositiveIntegerField(help_text='Units ordered for production')),
                ('received_quantity', models.PositiveIntegerField(default=0, help_text='Units actually received')),
                ('rejected_quantity', models.PositiveIntegerField(default=0, help_text='Units that failed QC')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit from factory', max_digits=15)),
                ('line_status', models.CharField(choices=[('pending', 'Pending'), ('in_production', 'In Production'), ('partially_received', 'Partially Received'), ('completed', 'Completed'), ('short_closed', 'Short Closed')], default='pending', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='mdm.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.productionorder')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_order_lines', to='mdm.sku')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_production_order_line',
                'ordering': ['created_at'],
                'unique_together': {('production_order', 'sku')},
            },
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['company', 'po_status'], name='inv_product_company_1fbc58_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['po_status', '-order_date'], name='inv_product_po_stat_43e08b_idx'),
        ),
    ]
