# Generated by Django 4.2.9 on 2026-02-16 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mdm', '0002_sku_size_alter_user_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('shop_domain', models.CharField(help_text='e.g., mystore.myshopify.com', max_length=255, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('api_version', models.CharField(default='2024-01', help_text='Shopify API version (e.g., 2024-01)', max_length=20)),
                ('auto_sync_products', models.BooleanField(default=True)),
                ('auto_sync_inventory', models.BooleanField(default=True)),
                ('auto_sync_orders', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.IntegerField(default=15)),
                ('last_product_sync', models.DateTimeField(blank=True, null=True)),
                ('last_inventory_sync', models.DateTimeField(blank=True, null=True)),
                ('last_order_sync', models.DateTimeField(blank=True, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_connection_test', models.DateTimeField(blank=True, null=True)),
                ('connection_error', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='mdm.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shopify_store',
            },
        ),
        migrations.CreateModel(
            name='ShopifyProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopify_product_id', models.BigIntegerField(db_index=True)),
                ('shopify_variant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('shopify_title', models.CharField(max_length=255)),
                ('shopify_sku', models.CharField(blank=True, max_length=255)),
                ('shopify_barcode', models.CharField(blank=True, max_length=255)),
                ('shopify_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('shopify_inventory_quantity', models.IntegerField(default=0)),
                ('shopify_data', models.JSONField(default=dict, help_text='Full Shopify product data')),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('error', 'Error')], default='pending', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('erp_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopify_products', to='mdm.product')),
                ('erp_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopify_products', to='mdm.sku')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='integrations.shopifystore')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shopify_product',
            },
        ),
        migrations.CreateModel(
            name='ShopifyInventoryLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopify_location_id', models.BigIntegerField(db_index=True)),
                ('shopify_location_name', models.CharField(max_length=255)),
                ('available', models.IntegerField(default=0)),
                ('on_hand', models.IntegerField(default=0)),
                ('committed', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('erp_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopify_inventory', to='mdm.location')),
                ('shopify_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='integrations.shopifyproduct')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='integrations.shopifystore')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shopify_inventory_level',
            },
        ),
        migrations.CreateModel(
            name='ShopifyWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=100)),
                ('shopify_id', models.BigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='integrations.shopifystore')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shopify_webhook_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'topic', '-created_at'], name='shopify_web_store_i_a6117c_idx'), models.Index(fields=['processed'], name='shopify_web_process_2b13d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopifyWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopify_webhook_id', models.BigIntegerField(unique=True)),
                ('topic', models.CharField(help_text='e.g., products/create, inventory_levels/update', max_length=100)),
                ('address', models.URLField(help_text='Webhook callback URL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='integrations.shopifystore')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shopify_webhook',
                'unique_together': {('store', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='ShopifySyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('products', 'Products'), ('inventory', 'Inventory'), ('orders', 'Orders'), ('full_sync', 'Full Sync')], max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('created_items', models.IntegerField(default=0)),
                ('updated_items', models.IntegerField(default=0)),
                ('failed_items', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='integrations.shopifystore')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shopify_sync_job',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['store', 'status', '-started_at'], name='shopify_syn_store_i_37617b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shopifystore',
            index=models.Index(fields=['company', 'status'], name='shopify_sto_company_353747_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyproduct',
            index=models.Index(fields=['store', 'sync_status'], name='shopify_pro_store_i_137fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyproduct',
            index=models.Index(fields=['shopify_sku'], name='shopify_pro_shopify_31b2ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopifyproduct',
            unique_together={('store', 'shopify_product_id', 'shopify_variant_id')},
        ),
        migrations.AddIndex(
            model_name='shopifyinventorylevel',
            index=models.Index(fields=['store', 'shopify_location_id'], name='shopify_inv_store_i_3f16c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopifyinventorylevel',
            unique_together={('shopify_product', 'shopify_location_id')},
        ),
    ]
