# Generated by Django 4.2.9 on 2026-02-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopifystore',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='shopifysyncjob',
            name='shopify_syn_store_i_37617b_idx',
        ),
        migrations.AddField(
            model_name='shopifysyncjob',
            name='job_status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_column='job_status', default='running', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopifysyncjob',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='shopifysyncjob',
            index=models.Index(fields=['store', 'job_status', '-started_at'], name='shopify_syn_store_i_4125f5_idx'),
        ),
    ]
