# Generated by Django 4.2.9 on 2026-02-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_shopifystore_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyproduct',
            name='shopify_product_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='shopify_tags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='shopify_vendor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
