# Generated by Django 4.2.9 on 2026-02-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_shopifyproduct_shopify_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyproduct',
            name='shopify_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
