# Generated by Django 4.2.9 on 2026-02-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_update_sync_job_type_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyproduct',
            name='shopify_inventory_item_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
