# Generated by Django 4.2.9 on 2026-03-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_shopifyproduct_shopify_inventory_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifysyncjob',
            name='job_status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_column='job_status', default='running', max_length=20),
        ),
    ]
