# Generated by Django 4.2.9 on 2026-03-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_update_job_status_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifysyncjob',
            name='job_type',
            field=models.CharField(choices=[('products', 'Products'), ('inventory', 'Inventory'), ('orders', 'Orders'), ('draft_orders', 'Draft Orders'), ('discounts', 'Discounts'), ('gift_cards', 'Gift Cards'), ('full_sync', 'Full Sync'), ('bulk_create_erp', 'Bulk Create ERP')], max_length=50),
        ),
    ]
