# Generated by Django 4.2.9 on 2026-03-11 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0013_alter_shopifysyncjob_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopify_collection_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=500)),
                ('collection_type', models.CharField(choices=[('custom', 'Custom Collection'), ('smart', 'Smart Collection')], default='custom', max_length=10)),
                ('handle', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='integrations.shopifystore')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shopify_collection',
                'ordering': ['title'],
                'unique_together': {('store', 'shopify_collection_id')},
            },
        ),
    ]
