# Generated by Django 4.2.9 on 2026-03-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_add_shopify_collection_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifysyncjob',
            name='job_type',
            field=models.CharField(choices=[('products', 'Products'), ('inventory', 'Inventory'), ('orders', 'Orders'), ('draft_orders', 'Draft Orders'), ('discounts', 'Discounts'), ('gift_cards', 'Gift Cards'), ('full_sync', 'Full Sync'), ('products_delta', 'Products Delta'), ('inventory_delta', 'Inventory Delta'), ('cleanup', 'Cleanup'), ('bulk_create_erp', 'Bulk Create ERP'), ('collections', 'Collections Sync')], max_length=50),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE shopify_sync_job DROP CONSTRAINT IF EXISTS shopify_sync_job_job_type_check;
                ALTER TABLE shopify_sync_job ADD CONSTRAINT shopify_sync_job_job_type_check 
                    CHECK (job_type IN ('products', 'inventory', 'orders', 'draft_orders', 'discounts', 'gift_cards', 'full_sync', 'products_delta', 'inventory_delta', 'cleanup', 'bulk_create_erp', 'collections'));
            """,
            reverse_sql="""
                ALTER TABLE shopify_sync_job DROP CONSTRAINT IF EXISTS shopify_sync_job_job_type_check;
                ALTER TABLE shopify_sync_job ADD CONSTRAINT shopify_sync_job_job_type_check 
                    CHECK (job_type IN ('products', 'inventory', 'orders', 'draft_orders', 'discounts', 'gift_cards', 'full_sync', 'products_delta', 'inventory_delta', 'cleanup', 'bulk_create_erp'));
            """,
        ),
    ]
