# Generated by Django 4.2.9 on 2026-03-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_update_job_type_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifycollection',
            name='collection_type',
            field=models.CharField(choices=[('custom', 'Custom Collection'), ('smart', 'Smart Collection'), ('virtual', 'Virtual (Taxonomy/Metafield)')], default='custom', max_length=10),
        ),
        migrations.AlterField(
            model_name='shopifysyncjob',
            name='job_type',
            field=models.CharField(choices=[('products', 'Products'), ('inventory', 'Inventory'), ('orders', 'Orders'), ('draft_orders', 'Draft Orders'), ('discounts', 'Discounts'), ('gift_cards', 'Gift Cards'), ('full_sync', 'Full Sync'), ('products_delta', 'Products Delta'), ('inventory_delta', 'Inventory Delta'), ('cleanup', 'Cleanup'), ('bulk_create_erp', 'Bulk Create ERP'), ('collections', 'Collections Sync'), ('virtual_sync', 'Virtual/Metafield Categorization'), ('sync_assignments', 'Collection Assignments Sync')], max_length=50),
        ),
    ]
