# Generated by Django 4.2.9 on 2026-02-13 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='size',
            field=models.CharField(blank=True, help_text='Size (e.g., S, M, L, XL, 28, 30, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='mdm.company'),
        ),
    ]
