# Generated by Django 4.2.9 on 2026-02-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0002_sku_size_alter_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='lifecycle_status',
            field=models.CharField(choices=[('proto', 'Proto / Design'), ('in_production', 'In Production'), ('active', 'Active / Sellable')], default='proto', max_length=20),
        ),
    ]
