# Generated by Django 4.2.9 on 2026-02-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0003_sku_lifecycle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
