# Generated by Django 4.2.9 on 2026-02-24 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0004_alter_company_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Auto-generated fabric SKU code', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Fabric name/description', max_length=255)),
                ('color', models.CharField(blank=True, help_text='Fabric color', max_length=100)),
                ('fabric_type', models.CharField(blank=True, help_text='Type of fabric (e.g. Cotton, Silk, Polyester)', max_length=100)),
                ('total_meters', models.DecimalField(decimal_places=2, default=0, help_text='Total meters of fabric received', max_digits=10)),
                ('used_meters', models.DecimalField(decimal_places=2, default=0, help_text='Meters already used/dispatched', max_digits=10)),
                ('cost_per_meter', models.DecimalField(decimal_places=2, default=0, help_text='Cost per meter in INR', max_digits=10)),
                ('photo_url', models.URLField(blank=True, help_text='Photo of the fabric')),
                ('pattern_url', models.URLField(blank=True, help_text='Designer pattern file URL')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('dispatch_unit', models.CharField(blank=True, help_text='Dispatch unit (A, B, C, etc.)', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Designer who approved/rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fabrics', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='mdm.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(blank=True, help_text='Auto-generated SKU for this fabric', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_source', to='mdm.sku')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrics', to='mdm.vendor')),
            ],
            options={
                'db_table': 'mdm_fabric',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'approval_status'], name='mdm_fabric_company_c536f2_idx'), models.Index(fields=['company', 'dispatch_unit'], name='mdm_fabric_company_a81fa0_idx')],
            },
        ),
    ]
