# Generated by Django 4.2.9 on 2026-02-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0005_create_fabric_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='pattern_url',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='fabric',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of the fabric', null=True, upload_to='fabrics/photos/'),
        ),
    ]
