# Generated by Django 4.2.9 on 2026-02-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0006_fabric_photo_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
