# Generated by Django 4.2.9 on 2026-02-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0007_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='store',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_type',
        ),
    ]
