# Generated by Django 4.2.9 on 2026-02-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0007_location_email_location_opening_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='offer_tag',
            field=models.CharField(choices=[('none', 'No Offer'), ('b1g1', 'Buy 1 Get 1 (B1G1)'), ('b2g1', 'Buy 2 Get 1 (B2G1)'), ('b3g1', 'Buy 3 Get 1 (B3G1)')], db_index=True, default='none', help_text='Promotional offer applied to this SKU', max_length=20),
        ),
    ]
