# Generated by Django 4.2.9 on 2026-02-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0007_location_email_location_opening_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary image for the product', null=True, upload_to='products/images/'),
        ),
    ]
