# Generated by Django 4.2.9 on 2026-02-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0009_remove_sku_offer_tag_location_offer_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='offer_tag',
        ),
    ]
