# Generated by Django 4.2.9 on 2026-02-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0011_location_offer_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='offer_mode',
            field=models.CharField(choices=[('all', 'All Products'), ('selected', 'Selected Products Only')], default='all', help_text='Whether the offer applies to all products or only chosen ones', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='offer_tag',
            field=models.CharField(choices=[('none', 'None'), ('b1g1', 'Buy 1 Get 1 (B1G1)'), ('b2g1', 'Buy 2 Get 1 (B2G1)'), ('b3g1', 'Buy 3 Get 1 (B3G1)')], default='none', help_text='The type of offer active at this location', max_length=20),
        ),
    ]
