# Generated by Django 4.2.9 on 2026-02-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0008_product_image'),
        ('mdm', '0012_location_offer_mode_alter_location_offer_tag'),
    ]

    operations = [
    ]
