# Generated by Django 4.2.9 on 2026-02-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0013_merge_20260226_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text='Mark as best seller for prioritized alerts'),
        ),
        migrations.AddField(
            model_name='sku',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Alert when stock falls below this level', max_digits=15),
        ),
        migrations.AddField(
            model_name='sku',
            name='movement_classification',
            field=models.CharField(choices=[('fast', 'Fast Moving'), ('slow', 'Slow Moving'), ('dead', 'Dead Stock'), ('none', 'Not Classified')], default='none', max_length=10),
        ),
    ]
