# Generated by Django 4.2.9 on 2026-03-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0014_sku_is_best_seller_sku_min_stock_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
