# Generated by Django 4.2.9 on 2026-03-11 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_add_shopify_collection_model'),
        ('mdm', '0015_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopify_collection',
            field=models.ForeignKey(blank=True, help_text='Shopify collection this product belongs to (used when pushing to Shopify)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='integrations.shopifycollection'),
        ),
    ]
