# Generated by Django 4.2.9 on 2026-02-16 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mdm', '0002_sku_size_alter_user_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('transaction_date', models.DateTimeField(db_index=True)),
                ('sales_channel', models.CharField(choices=[('store', 'Store'), ('online', 'Online'), ('mobile', 'Mobile App'), ('marketplace', 'Marketplace')], db_index=True, default='store', max_length=20)),
                ('register_number', models.CharField(blank=True, max_length=50)),
                ('customer_type', models.CharField(choices=[('walk-in', 'Walk-in'), ('member', 'Member'), ('vip', 'VIP')], default='walk-in', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('mixed', 'Mixed')], default='cash', max_length=20)),
                ('item_count', models.IntegerField(default=0)),
                ('processing_time_seconds', models.IntegerField(default=0)),
                ('campaign_code', models.CharField(blank=True, max_length=100)),
                ('referral_source', models.CharField(blank=True, max_length=100)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_processed', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='mdm.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_transactions', to='mdm.customer')),
                ('sales_associate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_assisted', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_transactions', to='mdm.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_transaction',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='ReturnTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('return_date', models.DateTimeField(db_index=True)),
                ('return_reason', models.CharField(max_length=255)),
                ('return_type', models.CharField(choices=[('refund', 'Refund'), ('exchange', 'Exchange'), ('store_credit', 'Store Credit')], default='refund', max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='mdm.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('original_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.salestransaction')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns_processed', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_transactions', to='mdm.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_return_transaction',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='StoreFootTraffic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('hour', models.IntegerField()),
                ('visitor_count', models.IntegerField(default=0)),
                ('entry_count', models.IntegerField(default=0)),
                ('exit_count', models.IntegerField(default=0)),
                ('transaction_count', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of visitors who made a purchase', max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='mdm.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foot_traffic', to='mdm.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_store_foot_traffic',
                'indexes': [models.Index(fields=['store', 'date'], name='sales_store_store_i_7b062c_idx')],
                'unique_together': {('company', 'store', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_date', models.DateField(db_index=True)),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='mdm.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_shifts', to='mdm.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_staff_shift',
                'ordering': ['-shift_date', 'clock_in'],
                'indexes': [models.Index(fields=['store', 'shift_date'], name='sales_staff_store_i_d9a35c_idx'), models.Index(fields=['employee', 'shift_date'], name='sales_staff_employe_ce864a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesTransactionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_returned', models.BooleanField(default=False)),
                ('return_reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_lines', to='mdm.sku')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salestransaction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_transaction_line',
                'ordering': ['line_number'],
                'unique_together': {('transaction', 'line_number')},
            },
        ),
        migrations.AddIndex(
            model_name='salestransaction',
            index=models.Index(fields=['company', 'sales_channel', '-transaction_date'], name='sales_trans_company_70414c_idx'),
        ),
        migrations.AddIndex(
            model_name='salestransaction',
            index=models.Index(fields=['store', '-transaction_date'], name='sales_trans_store_i_57d4fc_idx'),
        ),
        migrations.AddIndex(
            model_name='salestransaction',
            index=models.Index(fields=['transaction_date'], name='sales_trans_transac_488971_idx'),
        ),
        migrations.AddIndex(
            model_name='returntransaction',
            index=models.Index(fields=['company', 'store', '-return_date'], name='sales_retur_company_d64948_idx'),
        ),
    ]
