# Generated by Django 4.2.9 on 2026-02-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransactionline',
            name='return_condition',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
